spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.28.141.23:5432/sweatter
    username: beenavigator
    password: beenavigator123
#  jpa:
#    generate-ddl: true


  main:
    allow-circular-references: true

security:
  jwt:
    token:
      secret-key: rassrochkaApp
      expire-length: 14400000




