spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.28.141.23:5432/azamat
    username: sweatter
    password: 3edcVFR$
  jpa:
    generate-ddl: true